### ISSUE TITLE
Positioning widget

### ISSUE THREAD

**Issue by harbroe** [aigenseer/qr-scanner-redirect#16]
Hi - Thank you for this. It would really help me if it was possible to centre the widget in its Elementor container. I can only make it align left.

Again, thank you for it.

Richard

**Comment by aigenseer** [comment]
Hello Richard, 
you can send me an image or an example CSS code that this problem has fixed for you? 
Then maybe I can change something

**Comment by harbroe** [comment]
Hi

I was having the same problem with another shortcode, so searched. I 
discover you can centre it with the simple <center></center> html code, 
so have solved my own problem.

Thank you for the response, though. Best wishes,

Richard

Richard Harbroe Wright
27 West Street,
Seaford, BN25 1EE

01323 872857
www.rw2.co.uk


------ Original Message ------

**Comment by aigenseer** [comment]
Hallo Richard,

i think the best solution to center the button is that you add this lines in your css-code in your theme or in a css-file:

`
#qrscannerredirect
{
text-align: center;
}
`
if they not working use followed code:

`
#qrscannerredirect
{
display: flex;
justify-content: center;
}
`
Because not every plugin user wants the center button and your theme is responsible for the presentation.
